version: '3'

services:
    kagan-db:
        image: postgres:alpine
        environment:
            POSTGRES_PASSWORD: ${PG_PASS}
        ports:
            - ${PG_PORT}:${PG_PORT}
        container_name: kagan-db
        networks:
            - backend-network
    kagan-api:
        build:
            context: .
            args:
                - PORT=${PORT}
        image: kagan-api
        depends_on:
            - kagan-db
        environment:
            NODE_ENV: ${NODE_ENV}
            PG_HOST: kagan-db
            PG_USER: ${PG_USER}
            PG_PASS: ${PG_PASS}
            PG_PORT: ${PG_PORT}
            PG_DB: ${PG_DB}
            DB_SYNC: ${DB_SYNC}
            PROTECTED_ENVIRONMENTS: ${PROTECTED_ENVIRONMENTS}
            TOKEN: ${TOKEN}
        ports:
            - ${PORT}:${PORT}
        container_name: kagan-api
        networks:
            - backend-network
networks:
    backend-network:
        driver: bridge
